#
# Enable Bootstrap date picker and custom form types with default date format
#
twig:
    form:
        resources:
            - "SonataCoreBundle:Form:datepicker.html.twig"
    globals:
        ga_tracking: ~

sonata_admin:
    options:
        form_type: horizontal
    show_mosaic_button: false

sonata_core:
    form:
        mapping:
            type:
                sonata_type_date_range_picker: Cogitoweb\TemplateBundle\Form\Type\DateRangePickerType
                sonata_type_date_picker:       Cogitoweb\TemplateBundle\Form\Type\DatePickerType

doctrine:
    orm:
        dql:
            string_functions:
                ANY_ARRAY:     Cogitoweb\TemplateBundle\Query\Postgresql\Any
                OVERLAP_ARRAY: Cogitoweb\TemplateBundle\Query\Postgresql\Overlap