services:
    sonata.admin.orm.filter.type.string:
        class: Cogitoweb\TemplateBundle\Filter\CaseInsensitiveStringFilter
        tags:
            - { name: sonata.admin.filter.type, alias: doctrine_orm_string }